### ISSUE TITLE
URL is broken

### ISSUE THREAD

**Issue by mark0978** [fgallina/python-django.el#17]
See this blog post for a detailed quick start: http://from-the-cloud.com/en/emacs/2013/01/28_emacs-as-a-django-ide-with-python-djangoel.html

The above URL has been taken over by a domain squatter.

**Comment by hello-code** [comment]
Quick intro: ​http://from-the-cloud.com/en/emacs/2013/01/28_emacs-as-a-django-ide-with-python-djangoel.html

IS BROKEN !

**Comment by fgallina** [comment]
We need proper docs, in the meantime I replaced the link with archive.org one at c6fc521d
